<a href="https://colab.research.google.com/github/BrandonKTC/Pytorch_Deep_learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.0+cu113


In [ ]:
!nvidia-smi

Wed Jul 13 07:57:07 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P0    27W / 250W |      2MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Introduction to Tensors

In [ ]:
# Creating Tensors
# scalar
scalar = torch.tensor(7)
scalar, scalar.ndim, scalar.shape

(tensor(7), 0, torch.Size([]))

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector, vector.ndim, vector.shape

(tensor([7, 7]), 1, torch.Size([2]))

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX, MATRIX.ndim, MATRIX.shape

(tensor([[ 7,  8],
         [ 9, 10]]), 2, torch.Size([2, 2]))

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]],
                       [[19, 20, 21],
                        [22, 23, 24],
                        [25, 26, 27]]])
TENSOR, TENSOR.ndim, TENSOR.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]],
 
         [[19, 20, 21],
          [22, 23, 24],
          [25, 26, 27]]]), 3, torch.Size([3, 3, 3]))

### Random tensors

In [ ]:
# Create a random tensor (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape

(tensor([[0.1708, 0.3666, 0.8541, 0.7636],
         [0.0287, 0.9086, 0.3858, 0.7436],
         [0.1674, 0.8461, 0.1373, 0.2909]]), 2, torch.Size([3, 4]))

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(tensor([[[0.2549, 0.2462, 0.1281,  ..., 0.8994, 0.1616, 0.9289],
          [0.5716, 0.8201, 0.2026,  ..., 0.8049, 0.3397, 0.1195],
          [0.9338, 0.5569, 0.3508,  ..., 0.4906, 0.1318, 0.2388],
          ...,
          [0.0139, 0.7299, 0.9710,  ..., 0.3165, 0.8244, 0.2506],
          [0.2058, 0.9417, 0.6536,  ..., 0.5804, 0.6606, 0.5927],
          [0.6132, 0.6940, 0.5275,  ..., 0.6403, 0.8045, 0.2255]],
 
         [[0.6096, 0.1369, 0.4564,  ..., 0.5085, 0.0253, 0.0796],
          [0.0581, 0.6241, 0.5661,  ..., 0.3816, 0.5614, 0.8893],
          [0.5110, 0.4667, 0.6153,  ..., 0.3655, 0.3985, 0.0264],
          ...,
          [0.0932, 0.0295, 0.8769,  ..., 0.2093, 0.1112, 0.6456],
          [0.9862, 0.3383, 0.2180,  ..., 0.2714, 0.6386, 0.8176],
          [0.6756, 0.5761, 0.1548,  ..., 0.0509, 0.6741, 0.7241]],
 
         [[0.9547, 0.3067, 0.2838,  ..., 0.4121, 0.3941, 0.4042],
          [0.1557, 0.5549, 0.4370,  ..., 0.9806, 0.6283, 0.1017],
          [0.2735, 0.5382, 0.2615,  ...,

### Zeros and Ones

In [ ]:
zeros = torch.zeros((3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones((3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]), torch.float32)

### Creating a range of tensors

In [ ]:
# Old way (deprecating)
# one_to_ten = torch.range(1, 10)
one_to_ten = torch.arange(1, 10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # the datatype of the tensor
                               device=None, # What device is your tensor on
                               requires_grad=False) # wheter or not to track gradients of the tensor
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
mul = float_16_tensor * float_32_tensor
mul.dtype, mul.device
mul = torch.device('cuda')

### Squeeze, reshape, stack and unsqueeze Tensors

In [ ]:
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
x_stack = torch.stack([x,x,x,x], dim=0)
x_stack

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_squeeze = torch.squeeze(x_reshape)
x_squeeze, x_squeeze.shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_unsqueeze = torch.unsqueeze(x_squeeze, dim=-1)
x_unsqueeze, x_unsqueeze.shape

(tensor([[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]), torch.Size([9, 1]))

In [ ]:
x_original = torch.rand(size=(224, 224, 3))
x_original = x_original.permute(2, 0, 1)
x_original, x_original.shape

(tensor([[[0.5842, 0.7741, 0.8644,  ..., 0.4989, 0.4355, 0.6212],
          [0.5314, 0.8310, 0.2013,  ..., 0.7675, 0.9802, 0.6196],
          [0.4352, 0.5426, 0.0159,  ..., 0.9707, 0.3148, 0.7247],
          ...,
          [0.7331, 0.6136, 0.2919,  ..., 0.0074, 0.5384, 0.7987],
          [0.7759, 0.2546, 0.5616,  ..., 0.6076, 0.6896, 0.4863],
          [0.8685, 0.7501, 0.3527,  ..., 0.0780, 0.5195, 0.9025]],
 
         [[0.5349, 0.2463, 0.0893,  ..., 0.2907, 0.6347, 0.8017],
          [0.1805, 0.3105, 0.6133,  ..., 0.3830, 0.2258, 0.4672],
          [0.5141, 0.1814, 0.7891,  ..., 0.2967, 0.5823, 0.9261],
          ...,
          [0.0379, 0.7314, 0.0028,  ..., 0.1863, 0.4850, 0.0169],
          [0.3594, 0.6949, 0.9788,  ..., 0.5377, 0.0385, 0.8730],
          [0.8710, 0.0997, 0.3701,  ..., 0.1628, 0.2358, 0.7827]],
 
         [[0.4562, 0.2978, 0.1820,  ..., 0.9003, 0.0240, 0.6311],
          [0.7945, 0.9484, 0.7747,  ..., 0.0821, 0.5814, 0.7946],
          [0.3251, 0.9939, 0.1685,  ...,

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
x[:, :2, :2]

tensor([[[1, 2],
         [4, 5]]])

### Convert numpy array to torch tensor

In [ ]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(dtype=torch.float16)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float16))

In [ ]:
numpy_tensor = tensor.numpy()
numpy_tensor, tensor

(array([1., 2., 3., 4., 5., 6., 7.], dtype=float16),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float16))

In [ ]:
torch.manual_seed(42)

In [ ]:
import torch
torch.cuda.is_available()

True

## Putting tensors on the GPU

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3], device="cpu")

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Move tensor to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
tensor_cpu = tensor_on_gpu
tensor_cpu = tensor_cpu.to("cpu")
tensor_cpu.device

device(type='cpu')

# Pytorch Quick Start tutorial

In [ ]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [ ]:
# Download data from open datasets
training_data = datasets.FashionMNIST(root="data",
                                      train=True,
                                      download=True,
                                      transform=ToTensor())
test_data = datasets.FashionMNIST(root="data",
                                  train=False,
                                  download=True,
                                  transform=ToTensor())

  0%|          | 0/26421880 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/29515 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/4422102 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/5148 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [ ]:
BATCH_SIZE=64

# Create data loader
train_dataloader = DataLoader(training_data, batch_size=BATCH_SIZE)
test_dataloader = DataLoader(test_data, batch_size=BATCH_SIZE)

for X, y in test_dataloader:
  print(f"Shape of X [N, C, H, W]: {X.shape}")
  print(f"Shape of y: {y.shape} {y.dtype}")
  break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [ ]:
# Set the device
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

# Define model
class NeuralNetwork(nn.Module):
  def __init__(self):
    super(NeuralNetwork, self).__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28, 512),
        nn.ReLU(),
        nn.Linear(512, 512),
        nn.ReLU(),
        nn.Linear(512, 10)
    )

  def forward(self, x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits

model = NeuralNetwork().to(device)
print(model)

Using cuda device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [ ]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

def train(dataloader, model, loss_fn, optimizer):
  size = len(dataloader.dataset)
  model.train()
  for batch, (X, y) in enumerate(dataloader):
    X, y = X.to(device), y.to(device)

    # Compute prediction error
    pred = model(X)
    loss = loss_fn(pred, y)

    # Backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if batch % 100 == 0:
      loss, current = loss.item(), batch * len(X)
      print(f"loss: {loss:>7f} [{current:>5d}/{size:>5d}]")

In [ ]:
def test(dataloader, model, loss_fn):
  size = len(dataloader.dataset)
  num_batches = len(dataloader)
  model.eval()
  test_loss, correct = 0, 0
  with torch.no_grad():
    for X, y in dataloader:
      X, y = X.to(device), y.to(device)
      pred = model(X)
      test_loss += loss_fn(pred, y).item()
      correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
  print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f}\n")

In [ ]:
epochs = 5
for t in range(epochs):
  print(f"Epoch {t+1}\n -----------------------------")
  train(train_dataloader, model, loss_fn, optimizer)
  test(test_dataloader, model, loss_fn)``
print("Done!")

Epoch 1
 -----------------------------
loss: 2.309748 [    0/60000]
loss: 2.302063 [ 6400/60000]
loss: 2.275933 [12800/60000]
loss: 2.263258 [19200/60000]
loss: 2.255843 [25600/60000]
loss: 2.231278 [32000/60000]
loss: 2.233559 [38400/60000]
loss: 2.203418 [44800/60000]
loss: 2.202300 [51200/60000]
loss: 2.169956 [57600/60000]
Test Error: 
 Accuracy: 50.0%, Avg loss: 2.162398

Epoch 2
 -----------------------------
loss: 2.172232 [    0/60000]
loss: 2.169419 [ 6400/60000]
loss: 2.107579 [12800/60000]
loss: 2.123214 [19200/60000]
loss: 2.075258 [25600/60000]
loss: 2.021330 [32000/60000]
loss: 2.046261 [38400/60000]
loss: 1.967092 [44800/60000]
loss: 1.983540 [51200/60000]
loss: 1.911028 [57600/60000]
Test Error: 
 Accuracy: 57.0%, Avg loss: 1.898868

Epoch 3
 -----------------------------
loss: 1.930992 [    0/60000]
loss: 1.908100 [ 6400/60000]
loss: 1.784183 [12800/60000]
loss: 1.830026 [19200/60000]
loss: 1.718335 [25600/60000]
loss: 1.666553 [32000/60000]
loss: 1.696235 [38400/60000

## Saving And Load Models

In [ ]:
torch.save(model.state_dict(), "model.pth")

In [ ]:
loaded_model = NeuralNetwork()
loaded_model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

## Try the model

In [ ]:
classes = [
           "T-shirt/top",
           "Trouser",
           "Pullover",
           "Dress",
           "Coat",
           "Sandal",
           "Shirt",
           "Sneaker",
           "Bag",
           "Ankle boot"
]

model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
  pred = model(x.to(device))
  predicted, actual = classes[pred[0].argmax(0)], classes[y]
  print(f"Predicted: '{predicted}', Actual '{actual}'")

Predicted: 'Ankle boot', Actual 'Ankle boot'
